# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudstate/entity_key.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cloudstate/entity_key.proto',
  package='cloudstate',
  syntax='proto3',
  serialized_options=_b('\n\rio.cloudstate'),
  serialized_pb=_b('\n\x1b\x63loudstate/entity_key.proto\x12\ncloudstate\x1a google/protobuf/descriptor.proto:3\n\nentity_key\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08\x42\x0f\n\rio.cloudstateb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


ENTITY_KEY_FIELD_NUMBER = 50002
entity_key = _descriptor.FieldDescriptor(
  name='entity_key', full_name='cloudstate.entity_key', index=0,
  number=50002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['entity_key'] = entity_key
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(entity_key)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
