# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cloudstate import entity_pb2 as cloudstate_dot_entity__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EntityDiscoveryStub(object):
  """Entity discovery service.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.discover = channel.unary_unary(
        '/cloudstate.EntityDiscovery/discover',
        request_serializer=cloudstate_dot_entity__pb2.ProxyInfo.SerializeToString,
        response_deserializer=cloudstate_dot_entity__pb2.EntitySpec.FromString,
        )
    self.reportError = channel.unary_unary(
        '/cloudstate.EntityDiscovery/reportError',
        request_serializer=cloudstate_dot_entity__pb2.UserFunctionError.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class EntityDiscoveryServicer(object):
  """Entity discovery service.
  """

  def discover(self, request, context):
    """Discover what entities the user function wishes to serve.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def reportError(self, request, context):
    """Report an error back to the user function. This will only be invoked to tell the user function
    that it has done something wrong, eg, violated the protocol, tried to use an entity type that
    isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
    should be logged clearly for debugging purposes.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EntityDiscoveryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'discover': grpc.unary_unary_rpc_method_handler(
          servicer.discover,
          request_deserializer=cloudstate_dot_entity__pb2.ProxyInfo.FromString,
          response_serializer=cloudstate_dot_entity__pb2.EntitySpec.SerializeToString,
      ),
      'reportError': grpc.unary_unary_rpc_method_handler(
          servicer.reportError,
          request_deserializer=cloudstate_dot_entity__pb2.UserFunctionError.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cloudstate.EntityDiscovery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
