# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='domain.proto',
  package='com.example.shoppingcart.persistence',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x64omain.proto\x12$com.example.shoppingcart.persistence\"=\n\x08LineItem\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"I\n\tItemAdded\x12<\n\x04item\x18\x01 \x01(\x0b\x32..com.example.shoppingcart.persistence.LineItem\" \n\x0bItemRemoved\x12\x11\n\tproductId\x18\x01 \x01(\t\"E\n\x04\x43\x61rt\x12=\n\x05items\x18\x01 \x03(\x0b\x32..com.example.shoppingcart.persistence.LineItemb\x06proto3'
)




_LINEITEM = _descriptor.Descriptor(
  name='LineItem',
  full_name='com.example.shoppingcart.persistence.LineItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='com.example.shoppingcart.persistence.LineItem.productId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.example.shoppingcart.persistence.LineItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='com.example.shoppingcart.persistence.LineItem.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=115,
)


_ITEMADDED = _descriptor.Descriptor(
  name='ItemAdded',
  full_name='com.example.shoppingcart.persistence.ItemAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='com.example.shoppingcart.persistence.ItemAdded.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=190,
)


_ITEMREMOVED = _descriptor.Descriptor(
  name='ItemRemoved',
  full_name='com.example.shoppingcart.persistence.ItemRemoved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='com.example.shoppingcart.persistence.ItemRemoved.productId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=224,
)


_CART = _descriptor.Descriptor(
  name='Cart',
  full_name='com.example.shoppingcart.persistence.Cart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.example.shoppingcart.persistence.Cart.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=295,
)

_ITEMADDED.fields_by_name['item'].message_type = _LINEITEM
_CART.fields_by_name['items'].message_type = _LINEITEM
DESCRIPTOR.message_types_by_name['LineItem'] = _LINEITEM
DESCRIPTOR.message_types_by_name['ItemAdded'] = _ITEMADDED
DESCRIPTOR.message_types_by_name['ItemRemoved'] = _ITEMREMOVED
DESCRIPTOR.message_types_by_name['Cart'] = _CART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineItem = _reflection.GeneratedProtocolMessageType('LineItem', (_message.Message,), {
  'DESCRIPTOR' : _LINEITEM,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.persistence.LineItem)
  })
_sym_db.RegisterMessage(LineItem)

ItemAdded = _reflection.GeneratedProtocolMessageType('ItemAdded', (_message.Message,), {
  'DESCRIPTOR' : _ITEMADDED,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.persistence.ItemAdded)
  })
_sym_db.RegisterMessage(ItemAdded)

ItemRemoved = _reflection.GeneratedProtocolMessageType('ItemRemoved', (_message.Message,), {
  'DESCRIPTOR' : _ITEMREMOVED,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.persistence.ItemRemoved)
  })
_sym_db.RegisterMessage(ItemRemoved)

Cart = _reflection.GeneratedProtocolMessageType('Cart', (_message.Message,), {
  'DESCRIPTOR' : _CART,
  '__module__' : 'domain_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.persistence.Cart)
  })
_sym_db.RegisterMessage(Cart)


# @@protoc_insertion_point(module_scope)
