# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shoppingcart/shoppingcart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from cloudstate import entity_key_pb2 as cloudstate_dot_entity__key__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import http_pb2 as google_dot_api_dot_http__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shoppingcart/shoppingcart.proto',
  package='com.example.shoppingcart',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fshoppingcart/shoppingcart.proto\x12\x18\x63om.example.shoppingcart\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1b\x63loudstate/entity_key.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"X\n\x0b\x41\x64\x64LineItem\x12\x15\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\";\n\x0eRemoveLineItem\x12\x15\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"(\n\x0fGetShoppingCart\x12\x15\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\">\n\x08LineItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"9\n\x04\x43\x61rt\x12\x31\n\x05items\x18\x01 \x03(\x0b\x32\".com.example.shoppingcart.LineItem2\x94\x03\n\x0cShoppingCart\x12n\n\x07\x41\x64\x64Item\x12%.com.example.shoppingcart.AddLineItem\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/cart/{user_id}/items/add:\x01*\x12\x81\x01\n\nRemoveItem\x12(.com.example.shoppingcart.RemoveLineItem\x1a\x16.google.protobuf.Empty\"1\x82\xd3\xe4\x93\x02+\")/cart/{user_id}/items/{product_id}/remove\x12\x8f\x01\n\x07GetCart\x12).com.example.shoppingcart.GetShoppingCart\x1a\x1e.com.example.shoppingcart.Cart\"9\x82\xd3\xe4\x93\x02\x33\x12\x10/carts/{user_id}Z\x1f\x12\x16/carts/{user_id}/itemsb\x05itemsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,cloudstate_dot_entity__key__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_api_dot_http__pb2.DESCRIPTOR,])




_ADDLINEITEM = _descriptor.Descriptor(
  name='AddLineItem',
  full_name='com.example.shoppingcart.AddLineItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.example.shoppingcart.AddLineItem.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='com.example.shoppingcart.AddLineItem.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.example.shoppingcart.AddLineItem.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='com.example.shoppingcart.AddLineItem.quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=260,
)


_REMOVELINEITEM = _descriptor.Descriptor(
  name='RemoveLineItem',
  full_name='com.example.shoppingcart.RemoveLineItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.example.shoppingcart.RemoveLineItem.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='com.example.shoppingcart.RemoveLineItem.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=321,
)


_GETSHOPPINGCART = _descriptor.Descriptor(
  name='GetShoppingCart',
  full_name='com.example.shoppingcart.GetShoppingCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.example.shoppingcart.GetShoppingCart.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=363,
)


_LINEITEM = _descriptor.Descriptor(
  name='LineItem',
  full_name='com.example.shoppingcart.LineItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='com.example.shoppingcart.LineItem.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.example.shoppingcart.LineItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='com.example.shoppingcart.LineItem.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=427,
)


_CART = _descriptor.Descriptor(
  name='Cart',
  full_name='com.example.shoppingcart.Cart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.example.shoppingcart.Cart.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=486,
)

_CART.fields_by_name['items'].message_type = _LINEITEM
DESCRIPTOR.message_types_by_name['AddLineItem'] = _ADDLINEITEM
DESCRIPTOR.message_types_by_name['RemoveLineItem'] = _REMOVELINEITEM
DESCRIPTOR.message_types_by_name['GetShoppingCart'] = _GETSHOPPINGCART
DESCRIPTOR.message_types_by_name['LineItem'] = _LINEITEM
DESCRIPTOR.message_types_by_name['Cart'] = _CART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddLineItem = _reflection.GeneratedProtocolMessageType('AddLineItem', (_message.Message,), {
  'DESCRIPTOR' : _ADDLINEITEM,
  '__module__' : 'shoppingcart.shoppingcart_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.AddLineItem)
  })
_sym_db.RegisterMessage(AddLineItem)

RemoveLineItem = _reflection.GeneratedProtocolMessageType('RemoveLineItem', (_message.Message,), {
  'DESCRIPTOR' : _REMOVELINEITEM,
  '__module__' : 'shoppingcart.shoppingcart_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.RemoveLineItem)
  })
_sym_db.RegisterMessage(RemoveLineItem)

GetShoppingCart = _reflection.GeneratedProtocolMessageType('GetShoppingCart', (_message.Message,), {
  'DESCRIPTOR' : _GETSHOPPINGCART,
  '__module__' : 'shoppingcart.shoppingcart_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.GetShoppingCart)
  })
_sym_db.RegisterMessage(GetShoppingCart)

LineItem = _reflection.GeneratedProtocolMessageType('LineItem', (_message.Message,), {
  'DESCRIPTOR' : _LINEITEM,
  '__module__' : 'shoppingcart.shoppingcart_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.LineItem)
  })
_sym_db.RegisterMessage(LineItem)

Cart = _reflection.GeneratedProtocolMessageType('Cart', (_message.Message,), {
  'DESCRIPTOR' : _CART,
  '__module__' : 'shoppingcart.shoppingcart_pb2'
  # @@protoc_insertion_point(class_scope:com.example.shoppingcart.Cart)
  })
_sym_db.RegisterMessage(Cart)


_ADDLINEITEM.fields_by_name['user_id']._options = None
_REMOVELINEITEM.fields_by_name['user_id']._options = None
_GETSHOPPINGCART.fields_by_name['user_id']._options = None

_SHOPPINGCART = _descriptor.ServiceDescriptor(
  name='ShoppingCart',
  full_name='com.example.shoppingcart.ShoppingCart',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=489,
  serialized_end=893,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddItem',
    full_name='com.example.shoppingcart.ShoppingCart.AddItem',
    index=0,
    containing_service=None,
    input_type=_ADDLINEITEM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\202\323\344\223\002\036\"\031/cart/{user_id}/items/add:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='RemoveItem',
    full_name='com.example.shoppingcart.ShoppingCart.RemoveItem',
    index=1,
    containing_service=None,
    input_type=_REMOVELINEITEM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=_b('\202\323\344\223\002+\")/cart/{user_id}/items/{product_id}/remove'),
  ),
  _descriptor.MethodDescriptor(
    name='GetCart',
    full_name='com.example.shoppingcart.ShoppingCart.GetCart',
    index=2,
    containing_service=None,
    input_type=_GETSHOPPINGCART,
    output_type=_CART,
    serialized_options=_b('\202\323\344\223\0023\022\020/carts/{user_id}Z\037\022\026/carts/{user_id}/itemsb\005items'),
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOPPINGCART)

DESCRIPTOR.services_by_name['ShoppingCart'] = _SHOPPINGCART

# @@protoc_insertion_point(module_scope)
